universe = vanilla
log = $(dir).log
error = $(dir).err
#
executable = count.sh
arguments = $(dir)
output = $(dir).out
#
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#
# transfer_input_files = ../../global/samtools-1.3,/mnt/gluster/dgshrader/merged_bam/$(file)
# only use the following if downloading python .tar.gz from mnt/gluster doesn't work
transfer_input_files = ../../global/samtools-1.3,../../global/python,../../global/HTSeq-0.6.1,/mnt/gluster/dgshrader/TH_bam/$(dir)
#
request_cpus= 1
request_memory = 10 GB
request_disk = 5 GB
#
# +WantFlocking = true
# +WantGlideIn = true
# Requirements = Target.PoolName =!= "CHTC"
requirements = (Target.HasGluster == true) && (OpSys == "LINUX") && (OpSysMajorVer == 6)
#
queue dir from bamDirList.txt
