# submit file for mapping metagenomic time series reads to the coassembly.
# run from the TroutBogReads folder
# this sets up the relative location - you can run condor_submit from folders within the submit node
#

# minid = 92

universe = vanilla
log = $(file).log
error = $(file).err
#
executable = run_bbmap.sh
# arguments = $(file) $(minid)
arguments = $(file)
output = $(file).out
# $cluster-> $dir
# $process->$file
#
initialdir = $(dir)
# initialdir allows us to perform this action within each metagenome folder
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../../../global/bbmap_only,$(file)
#
request_cpus= 1
request_memory = 6 GB
request_disk = 3 GB
# +WantFlocking = true
# +WantGlideIn = true
# Requirements = Target.PoolName =!= "CHTC"
#
queue dir,file from readFileList.txt
# readFileList.txt is a space-separated text file. Folder name <space> metagenome read file fraction name
# e.g., one line would be "IHPN IHPNaa"
