# condor_submit -i interactive.sub
# Submit this script to run my bash script interactively from the execute node
# This will enable you to see errors directly and debug more efficienty.

universe = vanilla
# Name the log file:
log = interactive.log

# Name the files where standard output and error should be saved:
output = process.out
error = process.err

# Indicate all files that need to go into the interactive job session,
#  including any tar files that you prepared:
transfer_input_files = ../../python, preprocess_fasta.sh, FastaMLtoSL.py, TH_fasta_ID_test.txt

# It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".
request_cpus = 1
request_memory = 6GB
request_disk = 6GB

queue
