# submit file to preprocess Trout Bog Hypolimnion metagenomic read fasta files.

universe = vanilla 

executable = preprocess_fasta.sh
arguments = $(read)
output = run_output/$Fn(read).out
log = run_output/$Fn(read).log 
error = run_output/$Fn(read).err

transfer_input_files = ../../global/python, ../../global/FastaMLtoSL.py, ../../global/list_files.py
requirements = (Target.HasGluster == true) && (OpSys == "LINUX") && (OpSysMajorVer == 6)

request_cpus= 1
request_memory = 6 GB
request_disk =  10 GB

queue read from TH_fasta_ID.txt
