# condor_submit -i interactive.sub

universe = vanilla
log = interactive.log

# Name the files where standard output and error should be saved:
output = process.out
error = process.err

transfer_input_files = ../../global/samtools-1.3,../../global/python,../../global/HTSeq-0.6.1,count.sh

requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6) 

request_cpus = 1
request_memory = 6GB
request_disk = 6GB

queue
