# condor_submit -i interactive.sub
# Submit this script to run my bash script interactively from the execute node
# This will enable you to see errors directly and debug more efficiently.

universe = vanilla
# Name the log file:
log = interactive.log

# Name the files where standard output and error should be saved:
output = process.out
error = process.err

transfer_input_files = run_bbmap.sh,count.sh,../../global/bbmap_only,../../global/samtools-1.3,../../global/python,map_count.sh,IHPI/IHPIaa,IHPI/IHPIab,IHPI/IHPIac,IHPI/IHPIad,IHPI/IHPIae,IHPI/IHPIaf,IHPI/IHPIag,IHPI/IHPIah,IHPI/IHPIai

request_cpus = 1
request_memory = 6GB
request_disk = 3GB

queue
